version: '3'

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-postgres"
    restart: always
    volumes: 
      - ./banco-de-dados-agendamento:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: caaam
      POSTGRES_PASSWORD: espaco2501
      POSTGRES_DB: scheduling
